### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by 7b-w** [DaveSprague/SIPdev#1]
I have installed this SIP fork with the flow plugin. Everything seems to work except the flow plugin and when i select Arduino-Serial then submit the change, all I get is "Internal server error". Not sure why this is as I haven't made any changes to this fork of SIP and could use that flow plugin.
Any ideas what went wrong?
Thanks,
Bruce

**Comment by DaveSprague** [comment]
Do you have an Arduino connected to the RPi via USB?  If so, what type of
Arduino is it?  I think I have a gist showing the arduino code I use to
count pulses from the flow meters.

Here's the Arduino code.  It assumes there are up to eight flow sensors
with their signal wires connected to the arduino digital input pins 5 -
12.  I currently use it with three flow sensors.

**Comment by 7b-w** [comment]
Dave,

Thanks for the reply.

I am using a PRO MINI and a USB to TTL convertor from Sparkfun. This works fine

just using the Arduino IDE, plus I installed Putty on the Pi and ran a different program

on the Arduino and could see the output on the Putty window.

Is it necessary to have anything attached to the Arduino input pins? Is the SIP flow

plugin looking for a transition on the pins or a fixed level to continue with the program run?

Thanks,

Bruce

**Comment by DaveSprague** [comment]
The Arduino itself counts pulses coming from the flow sensors.

It is sent one of two commands from the RPi:

If the RPi sends "RS\n" . (the capital letters "R" and "S" followed by the
newline character),
then the Arduino resets all the counters to zero.

If the RPI sends "RD\n" then it expects the Arduino to send back a string
containing eight integer values (converted to strings), separated by
comma's and ending with the newline character '\n'.

For example, the Arduino might return:

"128, 12, 4300, 0, 0, 0, 333, 0\n"

and those values indicated how many pulses had been counted on the Arduino
digital pins 5 - 12 since the last time it received the "RS\n" (reset)
command from the RPi.

If the arduino isn't responding appropriately to the RS and RD commands
from the RPi, then it might stall when it hits the readline() statement.

The easiest thing would be for you to run that Arduino code that I linked
to in the gist here:
https://gist.github.com/DaveSprague/88c2380297e0ae53605ac360299f1b6b

I also see that it's expecting the Arduino to be on the virtual serial
port '/dev/ttyACM0'.  If it's on another tty port then the would probably
be an issue.

I hope this helps.

Dave

**Comment by 7b-w** [comment]
David,

This paragraph:

I also see that it's expecting the Arduino to be on the virtual serial
port '/dev/ttyACM0'. If it's on another tty port then the would probably
be an issue.

The Pi used /dev/ttyUSB0 as the port so where is it determined which port to use?

I saw /dev/ttyACM0 when I look for enabled ports on the Pi. If I attach a second

Arduino to the Pi via USB what port would that be ? /dev/ttyACM1 ? or /dev/ttyUSB1 ?

I use a keyboard and mouse hooked up to 2 of the USB ports ( my Pi has 4 ) so not

sure why I don’t see them when asking the Pi for USB port usage. I thought that was

/dev/ttyACM0 but that is not correct.

Thanks for your help, I like this SIP program and wish I knew more about adding my own

plugins.

Bruce

**Comment by DaveSprague** [comment]
Hi Bruce, I'm currently in Maine but my SIP RPi/Arduino irrigation system
is at our place in Arizona -- keeping our plants alive very reliably for
the past several years!  SIP is a great program.

I have an RPi here and an Arduino as well so in the next day or so I should
be able to track down how the port naming happens.  If you want to change
the code, the port name is set on line 103 in the "flow_sensors.py" plugin
file so you could make the change there and restart SIP and it should work.

If you have some idea of what kind of plugin you want to try, I could walk
you through it which would also help me refresh my memory on the
flow_sensor plugin and get back to work on it!

Thanks for the feedback,

Dave

**Comment by 7b-w** [comment]
Dave,

Thanks for getting back to me with the port info.

I should have time either later this week or weekend for sure as I want to get this SIP implemented 

ASAP since I am using those Orbit water timers and they leave a lot to be desired.

For the second Arduino it will be used to decode 433MHz OOK from sensors of soil moisture content and

soil temp. These will be solar powered and send the info at uneven times and the Pi will take that info and display it.

I already have the transmitter software working with the receiver but stopped at that point since I needed something to tie

it all together. SIP I think will do the tying nicely.

Bruce

**Comment by 7b-w** [comment]
Dave,

I changed line 103 to ttyUSB0 and finally got it to run without problem so far.

The only weird thing is don’t see in terminal window 8 values ( zero’s) as I see only

0 Gal/H so just one value. However when I run once I see the relay close and then the Gal/hour shows for station 01

so I would say its working but need to get a square wave on the Arduino pin and see the readings change.

So I am guessing a second Arduino would be ttyUSB1 but not ready to implement the moisture temp plugin just yet.

Thanks for your help!

Bruce

PS: took me a while to get things working since I have 2 keyboards and kept typing on the wrong one!

**Comment by 7b-w** [comment]
Here is a attached file of some errors when I start SIP with the flow_sensor.py script.

Still seems to work but again I don’t get a listing of all 8 flow values from the Arduino just 1

as I sent to you before (0 Gal/hour)

**Comment by DaveSprague** [comment]
Hi Bruce, I"ve been under the weather recently but i'll try to take a look at this soon.  I don't seem to see the an attached file.

**Comment by 7b-w** [comment]
Here it is in text format:

 

ALARM from Example_Sender!: Just and example!
flow sensors plugin loaded...
Settings initialized to: {'interface': 'Simulated', 'pulses_per_liter': 450.0, 'sensor_type': 'Seeed/Digiten 1/2 inch', 'units': 'Liters', 'rate_units': 'LpH'}
Updating settings from json file: {u'interface': u'Arduino-Serial', u'pulses_per_liter': 330.0, u'sensor_type': u'Seeed/Digiten 3/4 inch', u'units': u'Gallons', u'rate_units': u'GpH'}
resetting flow sensors
values from Arduino on establishing serial port

plugins loaded:
Unhandled exception in thread started by <function flow_sensor_loop at 0x7652dcb0>

Traceback (most recent call last):
  File "/home/pi/SIPdev/plugins/flow_sensors.py", line 84, in flow_sensor_loop
      flow_sensors
update_flow_values()
  File "/home/pi/SIPdev/plugins/flow_sensors.py", line 169, in update_flow_values
    print("elapsed time: " + str(elapsed_time))
NameError: global name 'elapsed_time' is not defined
  mobile_app
  plugin_manager
  relay_board
  signaling_examples
  system_update
http://0.0.0.0:80/
Starting timing loop

 

 

Here is a attached file of some errors when I start SIP with the flow_sensor.py script.

Still seems to work but again I don’t get a listing of all 8 flow values from the Arduino just 1

as I sent to you before (0 Gal/hour)

UPODATE: Using the Arduino serial monitor I can send RS which the shows the 8 values separated by commas and using a square wave

attached to pin 5 of the PRO Mini and sending RD I get a value in first spot and zero’s for others so the Arduino is working. When I try

to Run Once or run a program watering the flow shows up but there is no value being displayed. It’s like the SIP and Arduino are not

sending or receiving yet SIP must have “seen” the Arduino or I would be getting that error when trying to run the flow script.

**Comment by DaveSprague** [comment]
Hi Bruce,

The particular "unhandled exception you're getting is because I apparently changed the name of the variable that had been called 'elapsed_time' to 'elapsed_prev_read'.

In the live version of the flow_sensor plugin that print statement is commented out so you could either comment it out also or change the update the variable name from 'elapsed_time' to 'elapsed_prev_read'.

I committed a change to the flow_sensor.py plugin in the https://github.com/DaveSprague/sip_plugins repository but since you have your own version of the flow_sensors plugin (with the tty port change) you'll probably want to just change the variable name as above).

As I mentioned before, I can see any attached file.  Are you replying via email or on the github issues page for this respository (https://github.com/DaveSprague/SIPdev/issues/1)?

I don't know if email attachments come through but it you go to the issues page and add a new comment, you can just drag a file into the editor window to attach them

Dave

**Comment by 7b-w** [comment]
Thanks for getting back to me Dave and hope you are feeling better.

 

I replied via email to github address so I am guessing they stripped off the attachment. I will from now on use the comment window

and drag the file there.

 

I will change the name of that variable.

 

I still don’t know why I can’t see any GPH numbers when I test the run once or program a sequence in SIP. I see the flow info on the left

where S01 etc are but it shows zero, no number as I am sending a square wave to pin 5 of my Arduino. 

Using Arduino IDE and the serial monitor that is working when I send RS or RD I see zero’s on sending RS and the first number shows 

a number from my square wave input when sending RD.

Is there something else I need to enable or setup or check box to get the info to display numbers ( Gal/hour)?

**Comment by DaveSprague** [comment]
Hi Bruce, currently the addin only shows the GPH and Total Gallons when it is running a program either a program, a run-once program, or manually running it.  Can you send me screenshots of the your settings page for the flow_sensors and a screenshot of the home page when a program or run-once is running.  I want to make sure I understand what is showing up and what isn't.  Thanks!

**Comment by DaveSprague** [comment]
One other thought, on the Flow Sensor setting page, in addition to selection Arudino-Serial you also want to select one of the flow sensor types.  It doesn't matter which one at this point.  I think there's one that's selected by default but I don't remember for sure.

**Comment by 7b-w** [comment]
I selected the ¾ inch one.

**Comment by 7b-w** [comment]
Dave,

Been very busy here and not sure when I can get back to the flow issue. Maybe in a couple of weeks I can find the time

to fire up the Pi and take some snap shots of the screens I am seeing.

Thanks for your help so far,

Bruce

**Comment by 7b-w** [comment]
Hello Dave,

I found some time today to get some screen shots of the errors and what I am
seeing when running SIPdev

with flow sensor plug-in.

If I try and attach pictures GitHub will strip them off so is there a
different address I can use to send you the

screen shots?

Thanks,

Bruce

 

----------------------

Bruce W7BCW

Sultantronics

PO Box 1707

Sultan, WA. 98294

360-793-9513

**Comment by 7b-w** [comment]
Dave,
Here are a couple of screen shots of what I am seeing when I use your fork of SIP.
![Arduino flow RD](https://user-images.githubusercontent.com/36819830/61395372-257df900-a87a-11e9-9c96-4a9e0af36cec.jpg)
Here are some errors i am getting when i first start SIP on the Pi:
![SIP running page 2](https://user-images.githubusercontent.com/36819830/61395434-4a726c00-a87a-11e9-82ac-07d6b30b8567.jpg)
And here is the screen shot of the SIP program running on my laptop and run ounce screen shot, you can see the flow info but there is nothing displayed as value as I am sending a square wave to pin 5 of the Arduino PRO mini which works if you see the serial monitor screen shot previously.
![SIP running 2 min](https://user-images.githubusercontent.com/36819830/61395593-aa691280-a87a-11e9-934c-1fbec402400c.jpg)
Here is a screen shot of the run once screen where you can see there is no values displayed just zero's but the Arduino is working:
![SIP running 2 min](https://user-images.githubusercontent.com/36819830/61396173-f9637780-a87b-11e9-8ff1-db54fa15b8f4.jpg)
Oops, I already had that one loaded.
Here is the setup screen for the flow sensor:
![SIP flow settings](https://user-images.githubusercontent.com/36819830/61396279-36c80500-a87c-11e9-8505-c93dfa5c77fc.jpg)
So I hope you can give me some areas to check to get the flow sensor to show readings.
Thanks for now.
Bruce

**Comment by 7b-w** [comment]
Your comment on changing a variable name fixed the issue. I changed "elapsed_time" to "elapsed_prev_read" and I am now seeing flow values on the SIP page using "RUN ONCE". So I should have done that the last time i was checking on those errors I posted as that one change fixed all the errors.
So now to try and add a plugin of my own. Wish there was a "How to" on that subject.
Bruce

**Comment by 7b-w** [comment]
Interesting that a 3 Hz square wave gives a reading of 30 GPH flow rate.

**Comment by 7b-w** [comment]
I am using a function generator to simulate the flow sensor output.
